INSERT INTO
    companies (
        name,
        logo,
        industry,
        size,
        rating,
        locations,
        founded,
        description,
        employees,
        website,
        created_by
    )
VALUES (
        'TechCorp Inc.',
        '/logos/techcorp.png',
        'Technology',
        'Large',
        4.5,
        'San Francisco,New York,Austin',
        2010,
        'Tech company founded in 2010.',
        15000,
        'https://www.techcorpinc.com',
        'SYSTEM'
    ),
    (
        'Google',
        '/logos/google.png',
        'Technology',
        'Large',
        4.4,
        'Mountain View,New York,Seattle',
        1998,
        'Tech company founded in 1998.',
        156000,
        'https://www.google.com',
        'SYSTEM'
    ),
    (
        'Microsoft',
        '/logos/microsoft.png',
        'Technology',
        'Large',
        4.4,
        'Redmond,San Francisco,Austin',
        1975,
        'Tech company founded in 1975.',
        221000,
        'https://www.microsoft.com',
        'SYSTEM'
    ),
    (
        'Apple',
        '/logos/apple.png',
        'Technology',
        'Large',
        4.6,
        'Cupertino,Austin,Boston',
        1976,
        'Tech company founded in 1976.',
        164000,
        'https://www.apple.com',
        'SYSTEM'
    ),
    (
        'Amazon',
        '/logos/amazon.png',
        'E-commerce',
        'Large',
        4.2,
        'Seattle,New York,Austin',
        1994,
        'E-commerce company founded in 1994.',
        1540000,
        'https://www.amazon.com',
        'SYSTEM'
    ),
    (
        'Tesla',
        '/logos/tesla.png',
        'Automotive',
        'Large',
        4.3,
        'Palo Alto,Austin,Berlin',
        2003,
        'Automotive company founded in 2003.',
        127855,
        'https://www.tesla.com',
        'SYSTEM'
    ),
    (
        'Netflix',
        '/logos/netflix.png',
        'Entertainment',
        'Large',
        4.7,
        'Los Gatos,Los Angeles,New York',
        1997,
        'Entertainment company founded in 1997.',
        12800,
        'https://www.netflix.com',
        'SYSTEM'
    ),
    (
        'Meta',
        '/logos/meta.png',
        'Technology',
        'Large',
        4.1,
        'Menlo Park,Austin,London',
        2004,
        'Tech company founded in 2004.',
        86482,
        'https://www.meta.com',
        'SYSTEM'
    ),
    (
        'Spotify',
        '/logos/spotify.png',
        'Music',
        'Medium',
        4.5,
        'Stockholm,New York,Los Angeles',
        2006,
        'Music company founded in 2006.',
        9800,
        'https://www.spotify.com',
        'SYSTEM'
    ),
    (
        'Airbnb',
        '/logos/airbnb.png',
        'Travel',
        'Medium',
        4.4,
        'San Francisco,Portland,Dublin',
        2008,
        'Travel company founded in 2008.',
        6800,
        'https://www.airbnb.com',
        'SYSTEM'
    ),
    (
        'Uber',
        '/logos/uber.png',
        'Transportation',
        'Large',
        4.0,
        'San Francisco,New York,Amsterdam',
        2009,
        'Transport company founded in 2009.',
        32800,
        'https://www.uber.com',
        'SYSTEM'
    ),
    (
        'Slack',
        '/logos/slack.png',
        'Technology',
        'Medium',
        4.6,
        'San Francisco,New York,Toronto',
        2009,
        'Tech company founded in 2009.',
        2500,
        'https://www.slack.com',
        'SYSTEM'
    ),
    (
        'Zoom',
        '/logos/zoom.svg',
        'Technology',
        'Medium',
        4.5,
        'San Jose,Austin,Singapore',
        2011,
        'Tech company founded in 2011.',
        7400,
        'https://www.zoom.us',
        'SYSTEM'
    ),
    (
        'Shopify',
        '/logos/shopify.png',
        'E-commerce',
        'Medium',
        4.3,
        'Ottawa,Toronto,San Francisco',
        2006,
        'E-commerce company founded in 2006.',
        10000,
        'https://www.shopify.com',
        'SYSTEM'
    ),
    (
        'Stripe',
        '/logos/stripe.png',
        'Fintech',
        'Medium',
        4.7,
        'San Francisco,New York,London',
        2010,
        'Fintech company founded in 2010.',
        8000,
        'https://www.stripe.com',
        'SYSTEM'
    ),
    (
        'Square',
        '/logos/square.png',
        'Fintech',
        'Medium',
        4.2,
        'San Francisco,Atlanta,New York',
        2009,
        'Fintech company founded in 2009.',
        8000,
        'https://www.squareup.com',
        'SYSTEM'
    ),
    (
        'Coinbase',
        '/logos/coinbase.png',
        'Cryptocurrency',
        'Medium',
        4.1,
        'San Francisco,New York,London',
        2012,
        'Crypto company founded in 2012.',
        4700,
        'https://www.coinbase.com',
        'SYSTEM'
    ),
    (
        'Twilio',
        '/logos/twilio.png',
        'Technology',
        'Medium',
        4.3,
        'San Francisco,Denver,London',
        2008,
        'Tech company founded in 2008.',
        9100,
        'https://www.twilio.com',
        'SYSTEM'
    ),
    (
        'GitHub',
        '/logos/github.png',
        'Technology',
        'Medium',
        4.5,
        'San Francisco,Boston,Tokyo',
        2008,
        'Tech company founded in 2008.',
        3000,
        'https://www.github.com',
        'SYSTEM'
    ),
    (
        'Adobe',
        '/logos/adobe.svg',
        'Technology',
        'Large',
        4.4,
        'San Jose,Seattle,New York',
        1982,
        'Tech company founded in 1982.',
        29239,
        'https://www.adobe.com',
        'SYSTEM'
    ),
    (
        'Salesforce',
        '/logos/salesforce.png',
        'Technology',
        'Large',
        4.3,
        'San Francisco,Indianapolis,London',
        1999,
        'Tech company founded in 1999.',
        79390,
        'https://www.salesforce.com',
        'SYSTEM'
    ),
    (
        'Oracle',
        '/logos/oracle.png',
        'Technology',
        'Large',
        4.0,
        'Austin,Redwood City,Bangalore',
        1977,
        'Tech company founded in 1977.',
        164000,
        'https://www.oracle.com',
        'SYSTEM'
    ),
    (
        'IBM',
        '/logos/ibm.svg',
        'Technology',
        'Large',
        4.1,
        'Armonk,Austin,Bangalore',
        1911,
        'Tech company founded in 1911.',
        282100,
        'https://www.ibm.com',
        'SYSTEM'
    ),
    (
        'Intel',
        '/logos/intel.png',
        'Technology',
        'Large',
        4.2,
        'Santa Clara,Portland,Bangalore',
        1968,
        'Tech company founded in 1968.',
        131900,
        'https://www.intel.com',
        'SYSTEM'
    ),
    (
        'NVIDIA',
        '/logos/nvidia.png',
        'Technology',
        'Large',
        4.6,
        'Santa Clara,Austin,Tel Aviv',
        1993,
        'Tech company founded in 1993.',
        29600,
        'https://www.nvidia.com',
        'SYSTEM'
    );